name: Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 取得原始碼
      uses: actions/checkout@v3

    - name: 設定 Docker Hub 登入資訊
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 建立映像檔
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/2025cloud:gh-action .

    - name: 推送映像檔至 Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/2025cloud:gh-action
